services:
  - type: web
    name: ai-classroom-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python render_main.py
    plan: free
    envVars:
      - key: GOOGLE_AI_API_KEY
        value: AIzaSyCbJ8PlTK7UTCkKwCv1uVyM5RXnsMv4qLM
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0 